name: emcommon
dependencies:
- pip
- python=3.9
- pytest
- pytest-asyncio
- requests
- pip:
  # uses my fork until Transcrypt has a release w/ fix for https://github.com/TranscryptOrg/Transcrypt/issues/881
  - git+https://github.com/JGreenlee/Transcrypt@dont-redeclare-arguments
