# taken from https://github.com/e-mission/e-mission-server/blob/master/.github/workflows/test-with-manual-install.yml

name: pytest

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
  pull_request:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test-pytest:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install and start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: 4.4.0

    - uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        channels: bioconda, conda-forge, defaults
        use-only-tar-bz2: true  # IMPORTANT: This needs to be set for caching to work properly!
        auto-update-conda: true
        auto-activate-base: true

    - name: Check existing version of miniconda
      shell: bash -l {0}
      run: conda info -a

    - name: Install emcommon conda environment
      shell: bash -l {0}
      run: |
        # echo Test
        conda env update -n emcommon -f bin/environment.yml

    - name: Show current conda environment
      shell: bash -l {0}
      run: |
        conda activate emcommon && conda info --envs

    - name: Switch to emcommon and run the tests
      shell: bash -l {0}
      run: |
        conda activate emcommon
        PYTHONPATH=./src pytest test --asyncio-mode=auto

  test-jest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Install dependencies
      run: npm install

    - name: Run jest tests
      run: npx jest
